// Configuration file for theater reservation system
// Contains all application configuration including i18n strings and default settings

import type { AppConfig } from '../types/types';

// Internationalization (Dutch) - all UI text strings
export const i18n = {
    header: {
        title: '🎭 Diner Theater Reserveringen'
    },
    bookShow: {
        title: 'Voorstelling Boeken',
        selectShow: 'Kies een voorstelling:',
        selectDate: 'Selecteer datum:',
        selectTime: 'Selecteer tijd:',
        seatsAvailable: 'plaatsen beschikbaar',
        closedDate: 'Gesloten op deze datum',
        bookButton: 'Boek nu'
    },
    adminPanel: {
        title: 'Admin Beheer',
        showManagement: 'Voorstellingen Beheren',
        reservationsTitle: 'Reserveringen',
        showsTitle: 'Voorstellingen',
        configTitle: 'Configuratie',
        addShow: 'Nieuwe voorstelling toevoegen',
        editShow: 'Voorstelling bewerken',
        deleteShow: 'Verwijderen',
        toggleClosed: 'Open/Sluit',
        theaterBondsTitle: 'Theaterbonnen'
    },
    form: {
        name: 'Naam',
        email: 'E-mail',
        phone: 'Telefoon',
        address: 'Adres',
        city: 'Plaats',
        guests: 'Aantal gasten',
        specialRequests: 'Bijzondere verzoeken',
        submit: 'Reservering bevestigen',
        required: 'Verplicht veld'
    },
    reservation: {
        confirmationTitle: 'Reservering bevestigd!',
        confirmationText: 'Uw reservering is succesvol ontvangen.',
        reservationNumber: 'Reserveringsnummer',
        totalPrice: 'Totaalprijs',
        paymentInstructions: 'Betaalinstructies worden per e-mail verzonden.',
        paymentText: '💳 Betaling via iDEAL volgt per e-mail binnen 10 minuten.',
        thanksText: '🎭 Bedankt voor uw reservering! Tot ziens in het theater.',
        details: 'Reserveringsdetails',
        contact: 'Contactgegevens'
    },
    prices: {
        adult: 'Volwassenen',
        child: 'Kinderen (4-12)',
        senior: 'Senioren (65+)',
        perPerson: 'per persoon'
    },
    dates: {
        selectDate: 'Selecteer een datum',
        noShows: 'Geen voorstellingen beschikbaar'
    },
    errors: {
        fillAllFields: 'Vul alle verplichte velden in',
        invalidEmail: 'Ongeldig e-mailadres',
        invalidPhone: 'Ongeldig telefoonnummer',
        bookingFailed: 'Reservering mislukt. Probeer opnieuw.',
        loadingError: 'Fout bij laden van gegevens'
    },
    general: {
        loading: 'Laden...',
        save: 'Opslaan',
        cancel: 'Annuleren',
        edit: 'Bewerken',
        delete: 'Verwijderen',
        confirm: 'Bevestigen',
        back: 'Terug',
        next: 'Volgende',
        previous: 'Vorige',
        close: 'Sluiten',
        open: 'Openen',
        yes: 'Ja',
        no: 'Nee',
        search: 'Zoeken',
        filter: 'Filteren',
        sort: 'Sorteren',
        refresh: 'Vernieuwen',
        export: 'Exporteren',
        import: 'Importeren'
    },
    navigation: {
        home: 'Home',
        bookings: 'Reserveringen',
        admin: 'Admin',
        settings: 'Instellingen'
    },
    dashboard: {
        totalReservations: 'Totaal reserveringen',
        totalRevenue: 'Totale omzet',
        upcomingShows: 'Aankomende voorstellingen',
        todayReservations: "Vandaag's reserveringen"
    },
    merchandise: {
        title: 'Merchandise',
        addToCart: 'Toevoegen',
        removeFromCart: 'Verwijderen',
        cart: 'Winkelwagen',
        total: 'Totaal',
        checkout: 'Afrekenen',
        empty: 'Geen items geselecteerd',
        quantity: 'Aantal'
    },
    theaterVoucher: {
        title: 'Theaterbon',
        code: 'Boncode',
        enterCode: 'Voer boncode in',
        apply: 'Toepassen',
        value: 'Waarde',
        remaining: 'Resterend',
        expired: 'Verlopen',
        used: 'Gebruikt',
        invalid: 'Ongeldige code',
        success: 'Bon toegepast!'
    },
    // Additional properties needed for app functionality
    cancel: 'Annuleren',
    delete: 'Verwijderen',
    waitingList: 'Wachtlijst',
    fullyBooked: 'Wachtlijst Beschikbaar!',
    prevMonth: 'Vorige maand',
    nextMonth: 'Volgende maand',
    dayNames: ['Ma', 'Di', 'Wo', 'Do', 'Vr', 'Za', 'Zo'],
    addAction: 'Show Toevoegen',
    addShowEventTitle: 'Show Evenement Toevoegen',
    showName: 'Naam van de Show',
    showType: 'Type Show',
    date: 'Datum',
    capacity: 'Capaciteit',
    addShow: 'Show Toevoegen',
    showInfo: '{dayOfWeek}, {day} {month} {year} - {showType}',
    close: 'Sluiten',
    waitingListFormTitle: 'Show "{showName}" is gesloten voor boekingen',
    waitingListInfo: 'Deze show is momenteel gesloten voor nieuwe reserveringen. U kunt zich wel op de wachtlijst plaatsen. Wij nemen contact op als de show weer opengaat of er een plek vrijkomt.',
    waitingListConfirmed: 'U bent succesvol op de wachtlijst geplaatst!',
    fullName: 'Contactpersoon',
    numberOfGuests: 'Aantal personen',
    joinWaitingList: 'Plaats op Wachtlijst',
    bookingSummary: 'Overzicht Boeking',
    show: 'Show:',
    formPackage: 'Arrangement',
    standardPackage: 'Standaard Arrangement',
    packagePremium: 'Premium (incl. sterke drank, speciaalbier & bubbels)',
    packageStandard: 'Standaard (bier, wijn, fris, port & Martini)',
    premiumPackage: 'Premium Arrangement',
    formAddons: 'Leuke Extra\'s',
    promoCodeLabel: 'Promocode / Theaterbon',
    applyCode: 'Toepassen',
    subtotal: 'Subtotaal',
    discount: 'Korting',
    totalPrice: 'Totaalprijs',
    collapse: 'Inklappen',
    expand: 'Uitklappen',
    summaryOfYourBookingMobile: 'Bekijk Overzicht & Totaalprijs',
    codeApplied: 'Code \'{code}\' toegepast: {discount} korting.',
    voucherValidationError: 'Theaterbon fout: {error}',
    voucherAppliedSuccess: 'Theaterbon \'{code}\' succesvol toegepast (€{value})',
    invalidCode: 'Ongeldige of verlopen code.',
    awaitingApproval: 'Wacht op goedkeuring',
    provisionalBookingConfirm: 'Uw boeking is voorlopig en wacht op bevestiging',
    wizardStep1Title: 'Arrangement & Gasten',
    wizardStep1SubTitle: 'Kies uw arrangement en het aantal personen voor de show.',
    wizardStep2Title: 'Extra Drankjes',
    wizardStep2SubTitle: 'Let op: alleen beschikbaar voor groepen vanaf 25 personen.',
    addonMin25: '(vanaf 25 pers.)',
    wizardStep3Title: 'Leuke Extra\'s',
    wizardStep3SubTitle: 'Maak uw avond compleet met onze merchandise.',
    wizardStep4Title: 'Uw Gegevens',
    provisionalBookingWarning: 'Deze boeking overschrijdt de capaciteit',
    formCompany: '(Bedrijfs)naam',
    formSalutation: 'Aanhef',
    formContactPerson: 'Contactpersoon',
    formAddress: 'Adres',
    formHouseNumber: 'Huisnummer',
    formPostalCode: 'Postcode',
    formCity: 'Woonplaats',
    formPhone: 'Telefoon',
    formEmail: 'E-mail adres',
    formRemarks: 'Opmerkingen',
    celebrationName: 'Naam van feestvarken(s)',
    celebrationOccasion: 'Wat is er te vieren?',
    formConsent: 'Overig',
    consentNewsletter: 'Houd mij op de hoogte van leuke nieuwtjes',
    consentTerms: 'Ik ga akkoord met de Algemene voorwaarden',
    submitBooking: 'Boeking Voltooien',
    nextStep: 'Volgende',
    prevStep: 'Vorige',
    edit: 'Wijzig',
    wizardStep1: 'Gasten',
    wizardStep2: 'Drankenpakket', 
    wizardStep3: 'Extra\'s',
    wizardStep4: 'Gegevens',
    wizardStep5: '5. Overzicht',
    wizardStep5Title: 'Controleer uw boeking',
    bookForShow: 'Boeken voor {showName}',
    summaryOfYourBooking: 'Uw Reservering',
    yourSelection: 'Uw Keuze',
    reservationPendingConfirmation: 'Bedankt voor uw reservering!',
    reservationPendingSubtext: 'We zullen uw boeking zo spoedig mogelijk bekijken en u een definitieve bevestiging sturen.',
    reserveTable: 'Reserveer Uw Tafel',
    detailsFor: 'Details voor {dayOfWeek} {day} {month}',
    generateSummary: 'Genereer Dagelijkse Samenvatting',
    generating: 'Genereren...',
    aiSummary: 'AI Samenvatting',
    reservations: 'Reserveringen',
    guests: 'Gasten',
    actions: 'Acties',
    noReservations: 'Nog geen reserveringen voor deze datum.',
    selectDatePrompt: 'Selecteer een datum om details te bekijken.',
    selectDatePromptBooking: 'Selecteer een gemarkeerde datum op de kalender om de details te bekijken en te boeken.',
    instructions: 'Selecteer een gemarkeerde datum op de kalender om een show te boeken.',
    deleteConfirm: 'Weet u zeker dat u deze reservering wilt verwijderen?',
    apiKeyMissing: 'API Key ontbreekt.',
    aiError: 'Kon geen samenvatting genereren. Zie console voor details.',
    price: 'Prijs',
    waitingListAvailable: 'Show is vol? Geen probleem! 📝 Wachtlijst is nog beschikbaar - u krijgt bericht zodra er een plek vrijkomt!',
    noWaitingList: 'Niemand op de wachtlijst voor deze datum.',
    noShowOnDate: 'Geen show gepland op deze datum.',
    bulkDelete: 'Bulk Verwijderen',
    bulkDeleteTitle: 'Shows per maand verwijderen',
    deleteMode: 'Verwijder op basis van:',
    deleteByShowName: 'Op Shownaam',
    deleteByShowType: 'Op Showtype',
    deleteShows: 'Verwijder Show(s)',
    bulkDeleteWarning: 'WAARSCHUWING: Dit verwijdert alle \'{selection}\' shows en de bijbehorende reserveringen/wachtlijstplaatsen voor {month}. Deze actie kan niet ongedaan worden gemaakt. Weet u het zeker?',
    selectDates: 'Bulk Selecteer Datums',
    manageSelection: 'Beheer Selectie ({count})',
    cancelSelection: 'Annuleer Selectie',
    multiActionTitle: 'Acties voor Geselecteerde Datums',
    deleteAction: 'Shows Verwijderen',
    applyToAction: 'Actie Toepassen',
    deleteConfirmMulti: 'Weet u zeker dat u de shows op de {count} geselecteerde datums wilt verwijderen? Dit kan niet ongedaan worden gemaakt.',
    showTimes: 'Showtijden',
    settings: 'Instellingen',
    backToAdmin: 'Terug naar Admin Paneel',
    showsTypesCapacity: 'Shows, Types & Prijzen',
    bookingSettings: 'Boekingsinstellingen',
    pricingAndMerch: 'Extra\'s & Add-ons',
    packages: 'Pakketten & Bundels',
    borrels: 'Borrel Management',
    archive: 'Archief',
    showTitles: 'Show Titels',
    showTypes: 'Show Types & Prijzen',
    add: 'Toevoegen',
    pricing: 'Arrangement Prijzen',
    pricingPackages: 'Arrangementen',
    pricingWeekday: 'Doordeweeks (Zo-Do)',
    pricingWeekend: 'Weekend (Vr-Za)',
    pricingZorgHeld: 'Zorgzame Helden Avond',
    pricingAddons: 'Prijzen Extra\'s',
    merchandiseItemName: 'Naam Item',
    packageBuilder: 'Pakket Samensteller',
    createPackage: 'Nieuw Pakket',
    packageName: 'Pakket Naam',
    packageDescription: 'Beschrijving',
    originalPrice: 'Oorspronkelijke Prijs',
    packagePrice: 'Arrangement Prijs',
    packageItems: 'Pakket Items',
    dragItemsHere: 'Sleep items hiernaartoe',
    packagePreview: 'Pakket Voorbeeld',
    packageAnalytics: 'Pakket Statistieken',
    borrelManagement: 'Borrel Management',
    createBorrel: 'Nieuwe Borrel',
    preShowBorrel: 'Borrel Vooraf',
    postShowBorrel: 'Naborrel',
    borrelName: 'Borrel Naam',
    pricePerPerson: 'Prijs per Persoon',
    maxParticipants: 'Max Deelnemers',
    currentParticipants: 'Huidige Deelnemers',
    borrelLocation: 'Locatie',
    borrelDuration: 'Duur (minuten)',
    borrelIncludes: 'Inbegrepen',
    waitlistEnabled: 'Wachtlijst Actief',
    capSlogans: 'Spreuken op Petten',
    slogan: 'Slogan',
    saveChanges: 'Wijzigingen Opslaan',
    protected: 'Beschermd',
    addNew: 'Nieuwe Toevoegen',
    vouchers: 'Theaterbonnen',
    todayRevenue: 'Omzet Vandaag',
    todayGuests: 'Gasten Vandaag',
    nearlyFull: 'Bijna Volgeboekt',
    recentBookings: 'Recente Boekingen',
    viewCalendar: 'Kalender',
    backToDashboard: 'Terug naar Dashboard',
    kpiGuests: 'gasten',
    kpiShows: 'shows',
    noRecentBookings: 'Nog geen recentie boekingen.',
    noNearlyFullShows: 'Geen shows die bijna vol zijn.',
    archiveItem: 'Archiveer item',
    restoreItem: 'Haal item terug uit archief',
    defaultCapacity: 'Standaard Capaciteit',
    archivedShowNames: 'Gearchiveerde Showtitels',
    archivedShowTypes: 'Gearchiveerde Showtypes',
    noArchivedItems: 'Er zijn geen gearchiveerde items.',
    minGuestsPerBooking: 'Min. gasten per boeking',
    maxGuestsPerBooking: 'Max. gasten per boeking',
    bookingCutoffHours: 'Boekingen sluiten (uren vooraf)',
        bookingRules: 'Voorwaarden en regels voor boeken',
    
    // Show management
    deleteShow: 'Show verwijderen',
    deleteShowConfirm: 'Weet u zeker dat u deze show wilt verwijderen? Dit kan niet ongedaan worden gemaakt.',
    showDeleted: 'Show succesvol verwijdered',
    startCheckIn: 'Check-in starten',
    showClosedForBookings: 'Gesloten voor boekingen',
    showOpenForBookings: 'Open voor boekingen',
    
    // Reservation management
    status: 'Status', 
    approveBooking: 'Boeking goedkeuren',
    denyBooking: 'Boeking afwijzen',
    checkedIn: 'Ingecheckt',
    waiting: 'Wachtend',
    editReservation: 'Reservering bewerken',
    deleteConfirmation: 'Verwijdering bevestigen',
    
    // Lists and printing
    guestList: 'Gastenlijst',
    kitchenList: 'Keukenlijst', 
    printList: 'Lijst afdrukken',
    printableViewFor: 'Afdrukweergave voor {showName} op {date}',
    checkInStatus: 'Check-in status',
    checkedInCount: '{checkedIn} van {total} ingecheckt',
    checkIn: 'Inchecken',
    total: 'Totaal',
    arrangements: 'Arrangementen',
    specialRequests: 'Speciale verzoeken',
    
    // Customer management
    customerDetailTitle: 'Klantdetails',
    backToCustomers: 'Terug naar klanten',
    totalBookings: 'Totaal boekingen',
    totalSpent: 'Totaal uitgegeven',
    lastVisit: 'Laatste bezoek',
    bookingHistory: 'Boekingsgeschiedenis',
    
    // Approvals
    approvals: 'Goedkeuringen',
    approvalsDescription: 'Beheer boekingsgoedkeuringen',
    pendingApprovals: 'Wachtende goedkeuringen',
    approvedToday: 'Vandaag goedgekeurd',
    rejectedToday: 'Vandaag afgewezen',
    statusProvisional: 'Voorlopig',
    statusConfirmed: 'Bevestigd',
    statusCancelled: 'Geannuleerd',
    
    // Waitlist
    waitlist: 'Wachtlijst',
    waitlistDescription: 'Beheer wachtlijst voor uitverkochte shows',
    totalWaitlist: 'Totaal wachtlijst',
    statusActive: 'Actief',
    statusNotified: 'Geïnformeerd',
    statusConverted: 'Omgezet',
    statusExpired: 'Verlopen',
    notifyWaitlist: 'Wachtlijst informeren',
    convertToBooking: 'Omzetten naar boeking',
    removeFromWaitlist: 'Verwijderen van wachtlijst',
    
    // Voucher management
    voucherDeleteConfirm: 'Weet u zeker dat u deze voucher wilt verwijderen?',
    voucherArchiveConfirm: 'Weet u zeker dat u deze voucher wilt archiveren?',
    voucherRestoreConfirm: 'Weet u zeker dat u deze voucher wilt herstellen?',
    voucherArchived: 'Gearchiveerd',
    voucherActive: 'Actief',
    voucherUsed: 'Gebruikt',
    voucherExpired: 'Verlopen',
    voucherExpiringSoon: 'Verloopt binnenkort',
    theaterVouchers: 'Theater Vouchers',
    createVoucher: 'Voucher aanmaken',
    voucherCode: 'Vouchercode',
    voucherValue: 'Waarde',
    issueDate: 'Uitgiftedatum',
    expiryDate: 'Vervaldatum',
    voucherStatus: 'Status',
    voucherNotes: 'Notities',
    voucherEdit: 'Bewerken',
    extendExpiry: 'Vervaldatum verlengen',
    voucherRestore: 'Herstellen',
    voucherArchive: 'Archiveren',
    voucherDelete: 'Verwijderen',
    
    // Capacity and booking management
    overrideProtectionWarning: 'Bescherming overrullen waarschuwing',
    proceedAnyway: 'Toch doorgaan',
    bulkCapacityManagement: 'Bulk capaciteitsbeheer',
    capacityManagementTitle: 'Capaciteitsbeheer',
    capacityManagementDescription: 'Beheer capaciteit voor alle shows',
    thisWeek: 'Deze week',
    thisMonth: 'Deze maand',
    noShowsThisWeek: 'Geen shows deze week',
    noShowsThisMonth: 'Geen shows deze maand',
    booked: 'Geboekt',
    internal: 'Intern',
    external: 'Extern',
    remaining: 'Resterend',
    manualCapacityOverride: 'Handmatige capaciteitsaanpassing',
    addExternalBooking: 'Externe boeking toevoegen',
    
    // Settings and management
    settingsSaved: 'Instellingen opgeslagen',
    deleteItemConfirmTitle: 'Item verwijderen bevestigen',
    deleteItemConfirmMessage: 'Weet u zeker dat u dit item wilt verwijderen?',
    itemDeleted: 'Item verwijderd',
    archiveConfirmTitle: 'Archiveren bevestigen',
    archiveConfirmMessage: 'Weet u zeker dat u dit wilt archiveren?',
    settingsShowsDescription: 'Beheer beschikbare shows',
    settingsTypesDescription: 'Beheer showtypes en prijzen',
    priceStandard: 'Standaard prijs',
    pricePremium: 'Premium prijs',
    settingsBookingDescription: 'Boekingsinstellingen configureren',
    promoCodes: 'Promocodes',
    settingsPromoDescription: 'Beheer promocodes en kortingen',
    code: 'Code',
    discountAmount: 'Korting',
    typePercentage: 'Percentage',
    typeFixed: 'Vast bedrag',
    promoAndGifts: 'Promo & Cadeaus',
    save: 'Opslaan',
    
    // Navigation and views
    schedule: 'Planning',
    allReservations: 'Alle reserveringen',
    analytics: 'Analytics',
    customers: 'Klanten',
    capacityManagement: 'Capaciteitsbeheer', 
    reports: 'Rapporten',
    
    // Status messages
    reservationUpdated: 'Reservering bijgewerkt',
};

// Default application configuration
export const defaultConfig: AppConfig = {
    showNames: [
        { id: 'phantom', name: 'The Phantom of the Opera', archived: false, imageUrl: 'https://images.unsplash.com/photo-1596872147385-79d39c01a7d6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1200&q=80' },
        { id: 'lesmis', name: 'Les Misérables', archived: false, imageUrl: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1200&q=80' },
        { id: 'midsummer', name: 'A Midsummer Night\'s Dream', archived: false, imageUrl: 'https://images.unsplash.com/photo-1504387103973-e3d027eb551d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1200&q=80' },
        { id: 'wicked', name: 'Wicked', archived: true, imageUrl: 'https://placehold.co/600x300/1a1a1a/e6c35c?text=Wicked' },
    ],
    showTypes: [
        { id: 'weekday', name: 'Doordeweeks', archived: false, defaultCapacity: 220, priceStandard: 70, pricePremium: 85 },
        { id: 'weekend', name: 'Weekend Special', archived: false, defaultCapacity: 240, priceStandard: 80, pricePremium: 95 },
        { id: 'matinee', name: 'Matinee', archived: false, defaultCapacity: 200, priceStandard: 70, pricePremium: 85 },
        { id: 'premiere', name: 'Première', archived: false, defaultCapacity: 250, priceStandard: 90, pricePremium: 105 },
        { id: 'zorgheld', name: 'Zorgzame Helden Avond', archived: false, defaultCapacity: 200, priceStandard: 65, pricePremium: 80 },
    ],
    capSlogans: [
        "Meer pret in bed met een beetje vet",
        "Veel te dun is ook geen fun",
        "Lekker gluren naar de buren",
        "Mijn ziel heeft een ventiel",
        "Geen gezeik in onze wijk"
    ],
    merchandise: [
        { id: 'welcomePack', name: "'Welkom in de Buurt' Feestpakket", price: 10, imageUrl: 'https://placehold.co/150x150/2a2a2a/f0b429?text=Pakket' },
        { id: 'backpack', name: "Duurzame Rugzak", price: 5, imageUrl: 'https://placehold.co/150x150/2a2a2a/f0b429?text=Rugzak' },
        { id: 'ledHeadband', name: "LED Diadeem 'Ogen op Steeltjes'", price: 3.50, imageUrl: 'https://placehold.co/150x150/2a2a2a/f0b429?text=Diadeem' },
        { id: 'sunglasses', name: "Zonnebril 'Gluren naar de Buren'", price: 3.50, imageUrl: 'https://placehold.co/150x150/2a2a2a/f0b429?text=Zonnebril' },
        { id: 'foamstick', name: "Fun-Foamstick 'Zwieren & Zwaaien'", price: 2, imageUrl: 'https://placehold.co/150x150/2a2a2a/f0b429?text=Foamstick' },
        { id: 'flowerWreath', name: "Lichtgevende Bloemenkrans", price: 3.50, imageUrl: 'https://placehold.co/150x150/2a2a2a/f0b429?text=Krans' },
        { id: 'flowersForNeighbor', name: "De Buren in de Bloemen", price: 20, imageUrl: 'https://placehold.co/150x150/2a2a2a/f0b429?text=Bloemen' },
        { id: 'preShowDrinks', name: "Borrel Vooraf", price: 15 },
        { id: 'afterParty', name: "AfterParty", price: 15 },
    ],
    // 🛍️ NIEUWE MERCHANDISE SHOP DATA
    shopMerchandise: [
        {
            id: 'theater-tshirt-black',
            name: 'Theater Logo T-Shirt',
            description: 'Hoogwaardige katoenen t-shirt met het iconische theater logo. Comfortabel en stijlvol voor elke gelegenheid.',
            price: 24.95,
            originalPrice: 29.95,
            discount: 5,
            discountType: 'fixed',
            imageUrl: 'https://placehold.co/400x400/2a2a2a/f0b429?text=T-Shirt',
            galleryImages: ['https://placehold.co/400x400/2a2a2a/f0b429?text=T-Shirt+1', 'https://placehold.co/400x400/2a2a2a/f0b429?text=T-Shirt+2'],
            category: 'kleding',
            type: 'clothing',
            featured: true,
            stock: 125,
            stockStatus: 'in_stock',
            lowStockThreshold: 20,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
            colors: [
                { name: 'Zwart', hex: '#000000' },
                { name: 'Wit', hex: '#FFFFFF' },
                { name: 'Theater Goud', hex: '#f0b429' }
            ],
            rating: 4.8,
            reviewCount: 47,
            salesCount: 89,
            tags: ['premium', 'logo', 'cotton'],
            specifications: {
                'Materiaal': '100% Biologisch Katoen',
                'Pasvorm': 'Regulair',
                'Verzorging': 'Machinewasbaar 30°C'
            },
            isActive: true,
            createdAt: '2024-01-15T10:00:00Z',
            updatedAt: '2024-12-15T14:30:00Z'
        },
        {
            id: 'ceramic-mug',
            name: 'Theater Keramieke Mok',
            description: 'Prachtige handgemaakte keramieke mok met theater motief. Perfect voor uw favoriete warme drank.',
            price: 16.50,
            imageUrl: 'https://placehold.co/400x400/8b4513/f0b429?text=Mok',
            galleryImages: ['https://placehold.co/400x400/8b4513/f0b429?text=Mok+1'],
            category: 'accessoires',
            type: 'accessory',
            featured: true,
            stock: 78,
            stockStatus: 'in_stock',
            lowStockThreshold: 15,
            colors: [
                { name: 'Klassiek Wit', hex: '#FFFFFF' },
                { name: 'Theater Blauw', hex: '#2c5282' },
                { name: 'Warm Bruin', hex: '#8b4513' }
            ],
            rating: 4.6,
            reviewCount: 23,
            salesCount: 56,
            tags: ['keramiek', 'handgemaakt', 'gift'],
            specifications: {
                'Inhoud': '350ml',
                'Materiaal': 'Keramiek',
                'Verzorging': 'Vaatwasserbestendig'
            },
            isActive: true,
            createdAt: '2024-02-01T09:00:00Z',
            updatedAt: '2024-12-10T16:45:00Z'
        },
        {
            id: 'limited-poster',
            name: 'Limited Edition Poster "The Phantom"',
            description: 'Exclusieve limited edition poster van onze meest populaire voorstelling. Genummerd en gesigneerd.',
            price: 35.00,
            imageUrl: 'https://placehold.co/400x600/1a1a1a/e6c35c?text=Poster',
            category: 'verzamelobjecten',
            type: 'collectible',
            featured: true,
            stock: 12,
            stockStatus: 'low_stock',
            lowStockThreshold: 15,
            rating: 4.9,
            reviewCount: 8,
            salesCount: 18,
            tags: ['limited', 'collectible', 'signed'],
            specifications: {
                'Afmetingen': '50x70cm',
                'Materiaal': 'Premium Papier',
                'Oplage': 'Gelimiteerd tot 30 stuks'
            },
            isActive: true,
            createdAt: '2024-03-01T12:00:00Z',
            updatedAt: '2024-12-12T11:20:00Z'
        },
        {
            id: 'theater-wine',
            name: 'Theater Selection Wijn',
            description: 'Zorgvuldig geselecteerde wijn uit onze theater collectie. Perfect om thuis na te genieten.',
            price: 18.75,
            imageUrl: 'https://placehold.co/400x600/722f37/f0b429?text=Wijn',
            category: 'dranken',
            type: 'drink',
            featured: false,
            stock: 45,
            stockStatus: 'in_stock',
            lowStockThreshold: 10,
            rating: 4.4,
            reviewCount: 15,
            salesCount: 34,
            tags: ['premium', 'selection', 'wine'],
            specifications: {
                'Volume': '750ml',
                'Alcohol': '12.5%',
                'Herkomst': 'Frankrijk'
            },
            isActive: true,
            createdAt: '2024-04-01T08:00:00Z',
            updatedAt: '2024-12-08T13:15:00Z'
        },
        // 🍷 DRINKS & BORRELS - Voor boeking wizard
        {
            id: 'preShowDrinks',
            name: 'Borrel Vooraf',
            description: 'Geniet van een gezellige borrel voorafgaand aan de voorstelling. Perfect voor groepen vanaf 25 personen.',
            price: 15.00,
            originalPrice: 15.00,
            discount: 0,
            discountType: 'fixed',
            imageUrl: 'https://placehold.co/400x400/8b5cf6/white?text=Borrel',
            galleryImages: ['https://placehold.co/400x400/8b5cf6/white?text=Borrel+1'],
            category: 'dranken',
            type: 'drink',
            featured: true,
            stock: 999,
            stockStatus: 'in_stock',
            lowStockThreshold: 50,
            sizes: [],
            colors: [],
            rating: 4.5,
            reviewCount: 23,
            salesCount: 156,
            tags: ['borrel', 'groepsarrangement', 'premium'],
            specifications: {
                'Duur': '1 uur',
                'Minimum': '25 personen',
                'Inbegrepen': 'Premium drankjes selectie'
            },
            isActive: true,
            createdAt: '2024-01-15T10:00:00Z',
            updatedAt: '2024-12-10T14:20:00Z'
        },
        {
            id: 'afterParty',
            name: 'AfterParty',
            description: 'Verleng de avond met een exclusieve afterparty. Dans, drink en geniet na van een geweldige voorstelling.',
            price: 15.00,
            originalPrice: 15.00,
            discount: 0,
            discountType: 'fixed',
            imageUrl: 'https://placehold.co/400x400/7c3aed/white?text=Party',
            galleryImages: ['https://placehold.co/400x400/7c3aed/white?text=Party+1'],
            category: 'dranken',
            type: 'drink',
            featured: true,
            stock: 999,
            stockStatus: 'in_stock',
            lowStockThreshold: 50,
            sizes: [],
            colors: [],
            rating: 4.7,
            reviewCount: 31,
            salesCount: 98,
            tags: ['feest', 'groepsarrangement', 'exclusief'],
            specifications: {
                'Duur': '2-3 uur',
                'Minimum': '25 personen',
                'Inbegrepen': 'DJ, drankjes, snacks'
            },
            isActive: true,
            createdAt: '2024-01-15T10:00:00Z',
            updatedAt: '2024-12-10T14:20:00Z'
        }
    ],
    shopConfiguration: {
        displaySettings: {
            itemsPerPage: 12,
            gridColumns: { mobile: 1, tablet: 2, desktop: 4 },
            showPriceComparison: true,
            showStockLevels: true,
            enableWishlist: true,
            enableReviews: true,
            enableSocialSharing: true,
            defaultSortBy: 'featured'
        },
        categories: [
            { id: 'kleding', name: 'Kleding', icon: '👕', color: '#3b82f6', isActive: true },
            { id: 'accessoires', name: 'Accessoires', icon: '🎭', color: '#f59e0b', isActive: true },
            { id: 'verzamelobjecten', name: 'Verzamelobjecten', icon: '🏆', color: '#10b981', isActive: true },
            { id: 'eten', name: 'Eten', icon: '🍽️', color: '#ef4444', isActive: true },
            { id: 'dranken', name: 'Dranken', icon: '🍷', color: '#8b5cf6', isActive: true }
        ],
        filterOptions: {
            enablePriceFilter: true,
            priceRanges: [
                { min: 0, max: 15, label: 'Tot €15' },
                { min: 15, max: 30, label: '€15 - €30' },
                { min: 30, max: 50, label: '€30 - €50' },
                { min: 50, max: 999, label: 'Vanaf €50' }
            ],
            enableCategoryFilter: true,
            enableBrandFilter: false,
            enableRatingFilter: true,
            enableStockFilter: true
        },
        featuredSettings: {
            maxFeaturedItems: 6,
            autoRotateFeatured: false,
            featuredBadgeText: 'UITGELICHT',
            featuredBadgeColor: '#ef4444'
        }
    },
    // 🎁 BUNDEL SYSTEEM - Default bundels
    shopBundles: [
        {
            id: 'theater-starter-pack',
            name: 'Theater Starter Pack',
            description: 'Alles wat je nodig hebt voor je eerste theaterbezoek',
            items: [
                { itemId: 'theater-tshirt-black', quantity: 1 },
                { itemId: 'theater-mug-gold', quantity: 1 }
            ],
            originalTotalPrice: 39.94,
            bundlePrice: 34.95,
            discount: 4.99,
            discountType: 'fixed',
            imageUrl: 'https://placehold.co/400x400/f59e0b/white?text=Starter+Pack',
            category: 'bundels',
            featured: true,
            isActive: true,
            minQuantity: 1,
            maxQuantity: 10,
            createdAt: '2024-12-10T10:00:00Z',
            updatedAt: '2024-12-10T10:00:00Z'
        },
        {
            id: 'premium-experience',
            name: 'Premium Theater Ervaring',
            description: 'De ultieme theaterervaring met exclusieve items',
            items: [
                { itemId: 'theater-tshirt-black', quantity: 1 },
                { itemId: 'theater-mug-gold', quantity: 1 },
                { itemId: 'limited-poster', quantity: 1 }
            ],
            originalTotalPrice: 84.93,
            bundlePrice: 74.95,
            discount: 15,
            discountType: 'percentage',
            imageUrl: 'https://placehold.co/400x400/7c3aed/white?text=Premium',
            category: 'bundels',
            featured: true,
            isActive: true,
            minQuantity: 1,
            maxQuantity: 5,
            createdAt: '2024-12-10T10:00:00Z',
            updatedAt: '2024-12-10T10:00:00Z'
        }
    ],
    // 🏷️ DYNAMISCHE CATEGORIEËN
    shopCategories: [
        { id: 'kleding', name: 'Kleding & Accessoires', description: 'T-shirts, hoodies, accessoires', icon: '👕', color: '#10b981', order: 1, isActive: true, showInWizard: true, wizardOrder: 1 },
        { id: 'dranken', name: 'Drankjes & Borrels', description: 'Borrels, afterparty, drankjes', icon: '🍷', color: '#8b5cf6', order: 2, isActive: true, showInWizard: true, wizardOrder: 2 },
        { id: 'verzamelobjecten', name: 'Verzamelobjecten', description: 'Posters, signed items, specials', icon: '🎨', color: '#f59e0b', order: 3, isActive: true, showInWizard: true, wizardOrder: 3 },
        { id: 'bundels', name: 'Bundels & Pakketten', description: 'Voordelige combinaties', icon: '🎁', color: '#ef4444', order: 4, isActive: true, showInWizard: true, wizardOrder: 4 },
        { id: 'petten', name: 'Petten & Slogans', description: 'Gepersonaliseerde petten', icon: '🧢', color: '#6366f1', order: 5, isActive: true, showInWizard: false }
    ],
    // 🎨 WIZARD LAYOUT CONFIGURATIE
    wizardLayout: [
        {
            id: 'drinks-section',
            title: 'Drankjes & Borrels',
            description: 'Upgrade je ervaring met exclusieve drankjes',
            categoryIds: ['dranken'],
            displayType: 'list',
            itemsPerRow: 1,
            showPrices: true,
            showImages: true,
            showQuantity: false,
            order: 1,
            isActive: true
        },
        {
            id: 'bundles-section',
            title: 'Aanbevolen Pakketten',
            description: 'Voordelige bundels voor de perfecte theaterervaring',
            categoryIds: ['bundels'],
            displayType: 'grid',
            itemsPerRow: 2,
            showPrices: true,
            showImages: true,
            showQuantity: true,
            order: 2,
            isActive: true
        },
        {
            id: 'merchandise-section',
            title: 'Merchandise & Souvenirs',
            description: 'Neem een herinnering mee naar huis',
            categoryIds: ['kleding', 'verzamelobjecten'],
            displayType: 'grid',
            itemsPerRow: 3,
            showPrices: true,
            showImages: true,
            showQuantity: true,
            order: 3,
            isActive: true
        },
        {
            id: 'caps-section',
            title: 'Gepersonaliseerde Petten',
            description: 'Kies je favoriete slogan',
            categoryIds: ['petten'],
            displayType: 'grid',
            itemsPerRow: 4,
            showPrices: true,
            showImages: true,
            showQuantity: true,
            order: 4,
            isActive: true
        }
    ],
    // 🎁 Enhanced Package & Borrel Default Data
    merchandisePackages: [
        {
            id: 'complete_experience',
            name: 'Complete Theater Ervaring',
            description: 'Alles wat je nodig hebt voor een onvergetelijke avond',
            type: 'vip',
            items: [
                { merchandiseId: 'welcomePack', quantity: 1, required: true },
                { merchandiseId: 'backpack', quantity: 1, required: true },
                { merchandiseId: 'ledHeadband', quantity: 1, required: false },
                { merchandiseId: 'sunglasses', quantity: 1, required: false }
            ],
            originalPrice: 23,
            packagePrice: 18,
            discount: 22,
            discountType: 'percentage',
            minQuantity: 1,
            maxQuantity: 10,
            isActive: true,
            validFrom: '2024-01-01',
            validUntil: '2024-12-31',
            imageUrl: 'https://placehold.co/300x200/d4af37/2a2a2a?text=Complete+Pakket',
            tags: ['popular', 'complete', 'vip'],
            salesCount: 45,
            revenue: 810,
            category: 'popular'
        },
        {
            id: 'starter_pack',
            name: 'Starter Pakket',
            description: 'Perfect voor eerste bezoekers',
            type: 'merchandise',
            items: [
                { merchandiseId: 'welcomePack', quantity: 1, required: true },
                { merchandiseId: 'foamstick', quantity: 1, required: true }
            ],
            originalPrice: 12,
            packagePrice: 10,
            discount: 17,
            discountType: 'percentage',
            minQuantity: 1,
            maxQuantity: 20,
            isActive: true,
            validFrom: '2024-01-01',
            validUntil: '2024-12-31',
            imageUrl: 'https://placehold.co/300x200/2c5282/f0b429?text=Starter+Pakket',
            tags: ['beginners', 'popular'],
            salesCount: 78,
            revenue: 780,
            category: 'new'
        }
    ],
    borrelEvents: [
        {
            id: 'pre_show_aperitief',
            type: 'pre_show',
            name: 'Aperitief Vooraf',
            description: 'Geniet van een ontspannen drankje en hapje voor de voorstelling',
            pricePerPerson: 15,
            maxParticipants: 50,
            currentParticipants: 0,
            duration: 45,
            location: 'Theater Foyer',
            isActive: true,
            requiresReservation: true,
            waitlistEnabled: true,
            includes: ['Welcome drink', 'Amuse-bouches', 'Live muziek'],
            imageUrl: 'https://placehold.co/300x200/722f37/f0b429?text=Aperitief',
            salesCount: 23,
            revenue: 345
        },
        {
            id: 'post_show_afterparty',
            type: 'post_show',
            name: 'After Party',
            description: 'Sluit de avond af met een gezellige after party',
            pricePerPerson: 18,
            maxParticipants: 80,
            currentParticipants: 0,
            duration: 90,
            location: 'Theater Bar',
            isActive: true,
            requiresReservation: true,
            waitlistEnabled: false,
            includes: ['Cocktails', 'DJ muziek', 'Lichte snacks', 'Meet & greet cast'],
            imageUrl: 'https://placehold.co/300x200/8b4513/f0b429?text=After+Party',
            salesCount: 34,
            revenue: 612
        }
    ],
    enhancedMerchandise: [
        {
            id: 'theater_tshirt',
            name: 'Exclusief Theater T-shirt',
            price: 25,
            category: 'apparel',
            description: 'Hoogwaardige katoenen t-shirt met uniek theater ontwerp',
            images: ['https://placehold.co/300x300/2a2a2a/f0b429?text=T-shirt+Front', 'https://placehold.co/300x300/2a2a2a/f0b429?text=T-shirt+Back'],
            costPrice: 12,
            stockQuantity: 50,
            lowStockThreshold: 10,
            tags: ['apparel', 'exclusive', 'cotton'],
            salesData: {
                totalSold: 23,
                revenue: 575,
                conversionRate: 15.2,
                averageRating: 4.8
            },
            isActive: true,
            isFeatured: true,
            imageUrl: 'https://placehold.co/300x300/2a2a2a/f0b429?text=T-shirt'
        },
        {
            id: 'theater_program',
            name: 'Luxe Voorstellingsprogramma',
            price: 12,
            category: 'programs',
            description: 'Volledige cast informatie, achtergronden en prachtige foto\'s',
            images: ['https://placehold.co/300x400/1a365d/f0b429?text=Programma'],
            costPrice: 4,
            stockQuantity: 100,
            lowStockThreshold: 20,
            tags: ['program', 'collectible', 'photography'],
            salesData: {
                totalSold: 67,
                revenue: 804,
                conversionRate: 22.3,
                averageRating: 4.6
            },
            isActive: true,
            isFeatured: false,
            imageUrl: 'https://placehold.co/300x400/1a365d/f0b429?text=Programma'
        }
    ],
    promoCodes: [
        {id: 'promo1', code: 'ZOMER10', type: 'percentage', value: 10, isActive: true},
        {id: 'promo2', code: 'WELKOM5', type: 'fixed', value: 5, isActive: true},
    ],
    theaterVouchers: [
        // Voorbeelddata voor nieuwe theaterbon systeem
        {
            id: 'tv1',
            code: 'TB2024-A1B2',
            value: 100,
            issueDate: '2024-01-15',
            expiryDate: '2025-01-15',
            status: 'active',
            extendedCount: 0,
            notes: 'Nieuwjaarsactie'
        },
        {
            id: 'tv2',
            code: 'TB2024-C3D4',
            value: 50,
            issueDate: '2024-06-01',
            expiryDate: '2025-06-01',
            status: 'used',
            usedDate: '2024-08-15',
            usedReservationId: 123,
            extendedCount: 0
        },
    ],
    bookingSettings: {
        minGuests: 1,
        maxGuests: 20,
        bookingCutoffHours: 4,
    },
    prices: {
        preShowOrAfterParty: 15,
        cap: 5,
    }
};
